version = 0.1

[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::009087543814:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-yIPaEn8CtePF"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::009087543814:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-pHd1KNIg3tMU"
cloudformation_execution_role = "arn:aws:iam::009087543814:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-up6pwCSfkMkO"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-s9looib1rppb"
image_repository = ""
region = "us-west-2"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::009087543814:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-9pCFKL0N6vcZ"
cloudformation_execution_role = "arn:aws:iam::009087543814:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-Nf1uumxETGt6"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-uo9nkwcodsxr"
image_repository = ""
region = "us-west-2"
